# Generated by Django 2.2.14 on 2020-07-23 14:45

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirm',
            name='token',
            field=models.CharField(default=common.utils.uuid_create, max_length=32),
        ),
    ]
