# Generated by Django 2.2.14 on 2020-08-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200723_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirm',
            old_name='email',
            new_name='after_change_email',
        ),
    ]
