# Generated by Django 2.2.14 on 2020-08-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_favoritetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritetag',
            name='class_id',
        ),
    ]
