# Generated by Django 2.2.14 on 2020-08-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_favoritetag_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritetag',
            old_name='title',
            new_name='favorite_title',
        ),
        migrations.RenameField(
            model_name='favoritetag',
            old_name='url',
            new_name='favorite_url',
        ),
    ]
